---
name: Bug Report
about: Report a bug
title: '[BUG] '
labels: bug
assignees: ''
---

### Describe the bug



### Steps to reproduce

1.
2.
3.

### Expected behavior



### Device info

- Model:
- Android version:
- App version:

### Screenshots / logs

